### ISSUE TITLE
I can't get dual(con) of my AmplNLWriter model.

### ISSUE THREAD

**Issue by EdwardAngelino** [jump-dev/AmplNLWriter.jl#105]
`dual(con)
ArgumentError: ModelLike of type AmplNLWriter.Model{Float64} does not support accessing the attribute MathOptInterface.ConstraintDual(1)`

another is that

`dual_status(model)
NO_SOLUTION::ResultStatusCode = 0` 

is there another command?
Thks

**Comment by odow** [comment]
No, AmplNLWriter doesn't support accessing duals.

Use `Ipopt.jl` or `KNITRO.jl` (if you have a license).
