### ISSUE TITLE
Until Octeract develops a more custom Julia binding add it to AmplNLWriter

### ISSUE THREAD

**Issue by freemin7** [jump-dev/AmplNLWriter.jl#106]
Octeract provided this tutorial using AmplNLWriter: [https://octeract.com/how-to-use-jump-with-the-engine/](https://octeract.com/how-to-use-jump-with-the-engine/).
Can this be integrated into AmplWriter?

**Comment by odow** [comment]
> Can this be integrated into AmplWriter?

I don't know what you mean by this. It already works?

**Comment by mlubin** [comment]
Maybe we can add this link to https://jump.dev/JuMP.jl/dev/installation/?

**Comment by freemin7** [comment]
This package seemed to have provided named interfaces for Bonmin or IpOpt in the past. (such as BonminNLSolver)
Would it be possible/sensible to do the same for Oceract until a standalone library exists?

**Comment by odow** [comment]
> Would it be possible/sensible to do the same for Oceract until a standalone library exists?

We removed the `XXXNLSolver` interfaces because they were too complicated to install. If you require an Oceract solver, you could make a separate package that wrapped AmplNLWriter.

**Comment by freemin7** [comment]
Thanks, i wasn't aware of that change in policy.
