### ISSUE TITLE
Check :ExprGraph in features_available

### ISSUE THREAD

**Issue by freemin7** [jump-dev/AmplNLWriter.jl#107]
I am following this tutorial: [Cartpole.ipybn](https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl/blob/master/examples/Cartpole.ipynb)
but instead of using Ipopt i am trying to use a solver only accessible via AmplNLWriter. Instead of Block [17] i have
```
using AmplNLWriter
using MathOptInterface

const MOI = MathOptInterface

optimizer = AmplNLWriter.Optimizer("octeract-engine")

TrajectoryOptimization.build_MOI!(nlp, optimizer)
MOI.optimize!(optimizer)
MOI.get(optimizer, MOI.TerminationStatus())

```
I get the following stack trace:

```
MethodError: no method matching constraint_expr(::TrajOptNLP{4,1,Float64}, ::Int64)
Closest candidates are:
constraint_expr(!Matched::MathOptInterface.Test.FeasibilitySenseEvaluator, ::Int64) at /home/joto/.julia/packages/MathOptInterface/bygN7/src/Test/nlp.jl:204
constraint_expr(!Matched::MathOptInterface.Test.HS071, ::Int64) at /home/joto/.julia/packages/MathOptInterface/bygN7/src/Test/nlp.jl:37
constr_expr(::AmplNLWriter.NLPEvaluator{TrajOptNLP{4,1,Float64}}, ::Int64) at MOI_wrapper.jl:163
(::AmplNLWriter.var"#85#86"{AmplNLWriter.AmplNLMathProgModel})(::Int64) at AmplNLWriter.jl:211
iterate at generator.jl:47 [inlined]
_collect(::UnitRange{Int64}, ::Base.Generator{UnitRange{Int64},AmplNLWriter.var"#85#86"{AmplNLWriter.AmplNLMathProgModel}}, ::Base.EltypeUnknown, ::Base.HasShape{1}) at array.jl:678
collect_similar at array.jl:607 [inlined]
map at abstractarray.jl:2072 [inlined]
loadproblem!(::AmplNLWriter.AmplNLNonlinearModel, ::Int64, ::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol, ::AmplNLWriter.NLPEvaluator{TrajOptNLP{4,1,Float64}}) at AmplNLWriter.jl:210
optimize!(::AmplNLWriter.Model{Float64}) at MOI_wrapper.jl:371
top-level scope at Cartpole.jl:62
```
I opened the same issue at https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl/issues/33

**Comment by odow** [comment]
@freemin7 see my [comment](https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl/issues/33#issuecomment-662491547). You cannot use AmplNLWriter with TrajectoryOptimization. 

This issue can be fixed by throwing a nice error message if `:ExprGraph` is not available.

**Comment by odow** [comment]
This issue needs to be fixed.

**Comment by freemin7** [comment]
Thanks, i hoped using AmplNLWriter with TrajectoryOptimization was possible. 
Is this a restriction due to the file format or could this feature be added in principle.

**Comment by freemin7** [comment]
Has 
>  Given the complexity, that isn't feasible in the near term.

changed with Symbolics.jl from the MTK ecosystem which might be able to give you a full graph or is it still wait for JuMP 2.0's NLP ?

**Comment by mlubin** [comment]
If you figure out how to extract expression graphs using Symbolics.jl, you can add the constraints directly to JuMP in the raw expression format (https://jump.dev/JuMP.jl/v0.21.6/nlp/#Raw-expression-input). That JuMP model would then work with AmplNLWriter. I'd be very interested to see if you can make this work.
