### ISSUE TITLE
Support of User-Defined Functions from JuMP

### ISSUE THREAD

**Issue by MichaelLLi** [jump-dev/AmplNLWriter.jl#109]
Is there any support (or plans to support) user defined functions within the JuMP framework? The Bonmin algorithm (and KNITRO) should be able to run given just the function and derivative info, but I cannot seem to use the registered functions in JuMP with AmplNLWriter.

**Comment by odow** [comment]
> Is there any support (or plans to support) user defined functions within the JuMP framework?

No. AmplNLWriter writes an NL file, so it requires the expression graph of the functions.

The documentation should be updated to make this clearer.

**Comment by mlubin** [comment]
It's possible to compile libraries that AMPL can load and use for custom functions: https://ampl.com/MEETINGS/TALKS/2018_07_Valencia_WA-57.pdf. There are no plans to do this from AmplNLWriter, but if someone figures it out we could accept PRs.

**Comment by MichaelLLi** [comment]
Thanks so much for the pointers - I'll look into it!
