### ISSUE TITLE
long running time

### ISSUE THREAD

**Issue by jiawei92** [jump-dev/AmplNLWriter.jl#110]
I was trying to run a demo on my computer, which is shown below. However, a very long running time is needed even for this small problem

```
println("**********************************1************************************")

using JuMP, AmplNLWriter

println("**********************************2************************************")

m = Model(() -> AmplNLWriter.Optimizer("baron",["outlev=1"]))        # ,["outlev=1 keepsol"]


println("**********************************3************************************")

lb = [0,3,1,2,0,0,0]
ub = [10,20,2,4,10,201,100]
@variable(m, lb[i] ≤ x[i=1:7] ≤ ub[i])

println("**********************************4************************************")

@constraints(m, begin
    x[3]^2 + x[4]^2 ≤ 12
    x[1]^2 - x[2]^2 + x[4]^2 ≥ 3
    x[1]^2 - x[2]^2 + x[4]^2 ≤ 100
    x[1] + x[2] - 5x[3] + 2x[4] ≥ 10
    x[1] + x[2] - 5x[3] + 2x[4] ≤ 20
    x[4] - x[6]^2 + 4x[7]^2 ≤ 0
end)

println("**********************************5************************************")

@objective(m, Min, 6x[1] + 16x[2] - 9x[3] - 10x[4])

println("**********************************6************************************")

optimize!(m)

println("**********************************7************************************")
```

The running time needed for each section:
1->2: ~14 seconds
2->3: ~2 seconds
3->4: ~3 seconds
4->5: ~5 seconds
5->6: ~1 seconds
6->7: ~27 seconds

It needs about  52 seconds to run the script above, which seems very slow. I have checked log file of baron, showing that baron solver only used 0.05 seconds to solve the problem.

Is it normal?

**Comment by odow** [comment]
> Is it normal?

Yes. This is Julia's "Time-to-first-plot" issue. The first time you run code, it has to compile it. The second time you run it, it is fast.

See below:
```Julia
julia> @time using JuMP, AmplNLWriter
  5.676020 seconds (11.40 M allocations: 665.899 MiB, 4.39% gc time)

julia> @time using JuMP, AmplNLWriter
  0.000365 seconds (585 allocations: 37.000 KiB)

julia> function main()
           start = time()
           
           m = Model(() -> AmplNLWriter.Optimizer("/Users/Oscar/Desktop/bonmin"))
           
           @info "Took $(time() - start)"

           lb = [0,3,1,2,0,0,0]
           ub = [10,20,2,4,10,201,100]
           @variable(m, lb[i] ≤ x[i=1:7] ≤ ub[i])

           @info "Took $(time() - start)"

           @constraints(m, begin
               x[3]^2 + x[4]^2 ≤ 12
               x[1]^2 - x[2]^2 + x[4]^2 ≥ 3
               x[1]^2 - x[2]^2 + x[4]^2 ≤ 100
               x[1] + x[2] - 5x[3] + 2x[4] ≥ 10
               x[1] + x[2] - 5x[3] + 2x[4] ≤ 20
               x[4] - x[6]^2 + 4x[7]^2 ≤ 0
           end)

           @info "Took $(time() - start)"

           @objective(m, Min, 6x[1] + 16x[2] - 9x[3] - 10x[4])

           @info "Took $(time() - start)"

           optimize!(m)

           @info "Took $(time() - start)"
       end
main (generic function with 1 method)

julia> main()
[ Info: Took 0.6845381259918213
[ Info: Took 1.6197240352630615
[ Info: Took 1.9799301624298096
[ Info: Took 2.0059800148010254
Bonmin 1.8.7 using Cbc 2.10.3 and Ipopt 3.12.13
bonmin: 
Cbc3007W No integer variables - nothing to do

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

NLP0012I 
              Num      Status      Obj             It       time                 Location
NLP0014I             1         OPT 38.034253       36 0.014349
Cbc3007W No integer variables - nothing to do

 	"Finished"
[ Info: Took 18.58762502670288

julia> main()
[ Info: Took 0.00023698806762695312
[ Info: Took 0.0004398822784423828
[ Info: Took 0.000659942626953125
[ Info: Took 0.0009179115295410156
Bonmin 1.8.7 using Cbc 2.10.3 and Ipopt 3.12.13
bonmin: 
Cbc3007W No integer variables - nothing to do

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

NLP0012I 
              Num      Status      Obj             It       time                 Location
NLP0014I             1         OPT 38.034253       36 0.014026
Cbc3007W No integer variables - nothing to do

 	"Finished"
[ Info: Took 0.02907586097717285
```

In general, Julia is good if you want to pay the compilation time once, and then solve large or many problems. It is bad if you want to run a small script from the command line like `julia my_script.jl`.

Further reading:
- https://docs.julialang.org/en/v1/manual/performance-tips/
- https://www.reddit.com/r/Julia/comments/ek9cxq/enjoying_julia_but_why_does_it_take_30_seconds_to/
- https://discourse.julialang.org/t/roadmap-for-a-faster-time-to-first-plot/22956

**Comment by jiawei92** [comment]
> > Is it normal?
> 
> Yes. This is Julia's "Time-to-first-plot" issue. The first time you run code, it has to compile it. The second time you run it, it is fast.
> 
> See below:
> 
> ```julia
> julia> @time using JuMP, AmplNLWriter
>   5.676020 seconds (11.40 M allocations: 665.899 MiB, 4.39% gc time)
> 
> julia> @time using JuMP, AmplNLWriter
>   0.000365 seconds (585 allocations: 37.000 KiB)
> 
> julia> function main()
>            start = time()
>            
>            m = Model(() -> AmplNLWriter.Optimizer("/Users/Oscar/Desktop/bonmin"))
>            
>            @info "Took $(time() - start)"
> 
>            lb = [0,3,1,2,0,0,0]
>            ub = [10,20,2,4,10,201,100]
>            @variable(m, lb[i] ≤ x[i=1:7] ≤ ub[i])
> 
>            @info "Took $(time() - start)"
> 
>            @constraints(m, begin
>                x[3]^2 + x[4]^2 ≤ 12
>                x[1]^2 - x[2]^2 + x[4]^2 ≥ 3
>                x[1]^2 - x[2]^2 + x[4]^2 ≤ 100
>                x[1] + x[2] - 5x[3] + 2x[4] ≥ 10
>                x[1] + x[2] - 5x[3] + 2x[4] ≤ 20
>                x[4] - x[6]^2 + 4x[7]^2 ≤ 0
>            end)
> 
>            @info "Took $(time() - start)"
> 
>            @objective(m, Min, 6x[1] + 16x[2] - 9x[3] - 10x[4])
> 
>            @info "Took $(time() - start)"
> 
>            optimize!(m)
> 
>            @info "Took $(time() - start)"
>        end
> main (generic function with 1 method)
> 
> julia> main()
> [ Info: Took 0.6845381259918213
> [ Info: Took 1.6197240352630615
> [ Info: Took 1.9799301624298096
> [ Info: Took 2.0059800148010254
> Bonmin 1.8.7 using Cbc 2.10.3 and Ipopt 3.12.13
> bonmin: 
> Cbc3007W No integer variables - nothing to do
> 
> ******************************************************************************
> This program contains Ipopt, a library for large-scale nonlinear optimization.
>  Ipopt is released as open source code under the Eclipse Public License (EPL).
>          For more information visit http://projects.coin-or.org/Ipopt
> ******************************************************************************
> 
> NLP0012I 
>               Num      Status      Obj             It       time                 Location
> NLP0014I             1         OPT 38.034253       36 0.014349
> Cbc3007W No integer variables - nothing to do
> 
>  	"Finished"
> [ Info: Took 18.58762502670288
> 
> julia> main()
> [ Info: Took 0.00023698806762695312
> [ Info: Took 0.0004398822784423828
> [ Info: Took 0.000659942626953125
> [ Info: Took 0.0009179115295410156
> Bonmin 1.8.7 using Cbc 2.10.3 and Ipopt 3.12.13
> bonmin: 
> Cbc3007W No integer variables - nothing to do
> 
> ******************************************************************************
> This program contains Ipopt, a library for large-scale nonlinear optimization.
>  Ipopt is released as open source code under the Eclipse Public License (EPL).
>          For more information visit http://projects.coin-or.org/Ipopt
> ******************************************************************************
> 
> NLP0012I 
>               Num      Status      Obj             It       time                 Location
> NLP0014I             1         OPT 38.034253       36 0.014026
> Cbc3007W No integer variables - nothing to do
> 
>  	"Finished"
> [ Info: Took 0.02907586097717285
> ```
> 
> In general, Julia is good if you want to pay the compilation time once, and then solve large or many problems. It is bad if you want to run a small script from the command line like `julia my_script.jl`.
> 
> Further reading:
> 
> * https://docs.julialang.org/en/v1/manual/performance-tips/
> * https://www.reddit.com/r/Julia/comments/ek9cxq/enjoying_julia_but_why_does_it_take_30_seconds_to/
> * https://discourse.julialang.org/t/roadmap-for-a-faster-time-to-first-plot/22956

Thanks for your kind reply. Due to the high computational burden, I need to run my code on cloud clusters via command line. Does that mean Julia is not suitable for me? Or is there any workaround?

**Comment by odow** [comment]
> Due to the high computational burden, I need to run my code on cloud clusters via command line. Does that mean Julia is not suitable for me? Or is there any workaround?

Julia is perfect for this. The typical workarounds is just to start one Julia script and have it do a lot of work, instead of spawning many small Julia scripts.

The other thing you can do is to use [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl) to generate a system image. We did this for JuMP here: https://github.com/jump-dev/MOIPaperBenchmarks. See the `precompile.jl` file. Here's the relevant JuliaCon talk: https://www.youtube.com/watch?v=d7avhSuK2NA.

I'm going to close this issue since it isn't a bug in AmplNLWriter.jl. You should post on the Julia Forum (https://discourse.julialang.org) if you have further questions.
