### ISSUE TITLE
Couenne with JuMP: can’t evaluate pow”(0,1.5) 

### ISSUE THREAD

**Issue by ShuhuaGao** [jump-dev/AmplNLWriter.jl#111]
Hi, when playing with the example in Section 5 of Couenne's [documentation](https://github.com/coin-or/Couenne/blob/master/doc/couenne-user-manual.pdf), I get the following error 
```
ANALYSIS TEST: Error evaluating constraint 2: can't evaluate pow"(0,1.5).
```
which seems related to the constraint `x1^1.5 + 1.5*y3 == 3`. However, this problem was solved successfully in that documentation (not with JuMP).

Please check my question on [Julia discourse](https://discourse.julialang.org/t/couenne-with-jump-cant-evaluate-pow-0-1-5/48734) for more details. Could you suggest something for this issue?

**Comment by odow** [comment]
I'm going to close this issue to keep discussion focused on the discourse post. We can re-open if a bug is identified in AmplNLWriter.
