### ISSUE TITLE
About termination_status

### ISSUE THREAD

**Issue by ShuhuaGao** [jump-dev/AmplNLWriter.jl#114]
Let's consider the example in Couenne’s [documentation](https://github.com/coin-or/Couenne/blob/master/doc/couenne-user-manual.pdf) (Section 5). After calling `optimize!(model)`, the output info of Couenne is 
```
...
Clp0000I Optimal - objective value 7.6671801
 	"Finished"

Linearization cuts added at root node:         20
Linearization cuts added in total:             20  (separation time: 0s)
Total solve time:                           0.007s (0.007s in branch-and-bound)
Lower bound:                              7.66718
Upper bound:                              7.66718  (gap: 0.00%)
Branch-and-bound nodes:                         0
```
The obtained minimum is a global one, right?

If we check `termination_status(model)`, it shows
```
termination_status(model) = MathOptInterface.LOCALLY_SOLVED
```
According to JuMP documentation [here](https://jump.dev/JuMP.jl/stable/solutions/#MathOptInterface.TerminationStatusCode), if the global optimum is found, then the status should be `OPTIMAL: The algorithm found a globally optimal solution.`. 

1. How to explain the above inconsistency? Is it a bug?

2. `@show objective_value(model)` yields `objective_value(model) = 7.667180068813135`. Is there an option in Couenne that controls the precision of the result? E.g, higher precision at the cost of more computations. 

Thank you.

**Comment by odow** [comment]
> How to explain the above inconsistency?

AmplNLWriter doesn't know that Couenne is a global optimizer, and AMPL provides no way of ascertaining that. It's up to you to interpret `LOCALLY_SOLVED` as `OPTIMAL` if you know you have a solver that returns global optima.

The same issue occurs with Ipopt if you have a convex problem. Ipopt will return a global optima, but we still return `LOCALLY_SOLVED`.

> Is there an option in Couenne that controls the precision of the result?

I'm not sure. You should check the Couenne documentation.

**Comment by ShuhuaGao** [comment]
Got it. Thank you. 👍
