### ISSUE TITLE
How to get the solver's output information?

### ISSUE THREAD

**Issue by ShuhuaGao** [jump-dev/AmplNLWriter.jl#115]
Hi, I am using Couenne with AmplNLWriter.jl and JuMP. It works well. For my specific task, Couenne prints the following information
```
...
 	"Finished"

Linearization cuts added at root node:        567
Linearization cuts added in total:            567  (separation time: 0.001s)
Total solve time:                            0.65s (0.65s in branch-and-bound)
Lower bound:                           2.52782e-05
Upper bound:                           2.52782e-05  (gap: 0.00%)
Branch-and-bound nodes:                         2
...
```
1. Can we get the above `Lower bound` and `Upper bound` from an AmplNLWriter model in JuMP?
2. If not,  does AmplNLWriter cache the information printed above? Can we get the above message in a `String` form? 

I see from the source code that a struct [`AmplNLMathProgModel`](https://github.com/jump-dev/AmplNLWriter.jl/blob/master/src/AmplNLWriter.jl#L88) has the following fields:
```julia
    status::Symbol
    solve_exitcode::Int
    solve_result_num::Int
    solve_result::String
    solve_message::String
    solve_time::Float64
```
but I am not sure whether the above fields are related to what I am talking here. Besides, I do not find the documentation on how to get the `AmplNLMathProgModel` in JuMP.

**Comment by odow** [comment]
No, you cannot get this information from AmplNLWriter. It is printed to `stdout` by the Couenne executable. If you really need this, you could use `redirect_stdout` and then parse the output.

**Comment by ShuhuaGao** [comment]
Hi, @odow. Noted with thanks. In that case, I will parse the output.
