### ISSUE TITLE
Error Message with Incorrect Executable Specified

### ISSUE THREAD

**Issue by ccoffrin** [jump-dev/AmplNLWriter.jl#153]
This program's output confused me,
```
import JuMP, AmplNLWriter
model = JuMP.Model(() -> AmplNLWriter.Optimizer("foo"))
JuMP.@variable(model, x)
JuMP.@objective(model, Min, x^2)
JuMP.optimize!(model)
# everything is fine so far!
cost = JuMP.objective_value(model)
# ERROR: Result index of attribute MathOptInterface.ObjectiveValue(1) out of bounds. There are currently 0 solution(s) in the model.
```
I was expecting at the point of `optimize!(model)` to get an error if there was some issue calling `foo`.  Instead the issue does not appear to come up until `objective_value(model)`.  In a less obvious example, it took some time for me to understand that `foo` was the root cause.

Thoughts?

**Comment by odow** [comment]
You should look at `termination_status(model)` and then `raw_status_string(model)`. We've gone the route of not throwing an error in `optimize!`.

**Comment by ccoffrin** [comment]
Ok.  So if my workflow was originally,
```
model = JuMP.Model(() -> AmplNLWriter.Optimizer("foo"))
...
JuMP.optimize!(model)
cost = JuMP.objective_value(model)
```

I am thinking it should be instead,
```
model = JuMP.Model(() -> AmplNLWriter.Optimizer("foo"))
...
JuMP.optimize!(model)
if JuMP.primal_status(model) == JuMP.NO_SOLUTION
    error("my helpful message...")
end
cost = JuMP.objective_value(model)
```

**Comment by odow** [comment]
Yes. You should never query solutions without check the status. Perhaps something like:
```julia
if JuMP.primal_status(model) == JuMP.NO_SOLUTION
    error("No solution found. Solver reports: $(JuMP.raw_status(model))")
end
```

**Comment by ccoffrin** [comment]
Got it!  Thanks.
