### ISSUE TITLE
How to supress Couenne output

### ISSUE THREAD

**Issue by felipemarkson** [jump-dev/AmplNLWriter.jl#158]
Hi guys!

I'm trying to use `AmplNLWriter.jl` with Couenne and suppress all the output.

I've tried the  JuMP's `set_silent`, but I realize that the solver does not support it.

I also tried the code below, but without success

```julia
opt = optimizer_with_attributes(
    () -> AmplNLWriter.Optimizer(Couenne_jll.amplexe),
    "outlev" => 0,
)
set_optimizer(model, opt)
```

Any tips to suppress Couenne output?

**Comment by odow** [comment]
The options for Couenne are here: https://github.com/coin-or/Couenne/blob/master/src/couenne.opt

I guess you'd have to play with a few of them, and perhaps also some of the Ipopt and Bonmin options.

Links are here: https://github.com/jump-dev/AmplNLWriter.jl#options

**Comment by felipemarkson** [comment]
Ok! Thanks! I made some tests and I just give up... I'm moving to Juniper.jl
