### ISSUE TITLE
Where to put couenne.opt file?

### ISSUE THREAD

**Issue by avinashresearch1** [jump-dev/AmplNLWriter.jl#161]
Thanks for the interface! I am having a bit of trouble getting the solver options file (couenne.opt) to be recognized with JuMP. Specifically, I only want to set up the `time_limit` to be a few seconds.

**Comment by odow** [comment]
See https://github.com/jump-dev/AmplNLWriter.jl#opt-files

> This file must be located in the current working directory whenever the model is solved.


Note that I think if you set a time limit for Couenne it doesn't report output: https://github.com/jump-dev/AmplNLWriter.jl/issues/160

**Comment by odow** [comment]
Closing because this seems resolved.
