### ISSUE TITLE
Support MOI.TimeLimitSec

### ISSUE THREAD

**Issue by mzy2240** [jump-dev/AmplNLWriter.jl#165]
```julia
model = Model(() -> AmplNLWriter.Optimizer("/Users/xxx/Downloads/AMPL/gurobi"))
set_time_limit_sec(model, 600.0)
```
When using gurobi with AMPL, `set_time_limit_sec` will raise 

`MathOptInterface.UnsupportedAttribute{MathOptInterface.TimeLimitSec}: Attribute MathOptInterface.TimeLimitSec() is not supported by the model`

Considering many users may actually use Gurobi/CPLEX/XPRESS/COPT with AMPL license, can we provide a generic attribute `TimeLimitSec` similar to `COPT.jl` `Gurobi.jl`?

**Comment by odow** [comment]
We can't do this in AmplNLWriter because there is no way to set this uniformly across solvers via the AMPL interface.

You'll need to use `set_optimizer_attribute(model, "xxx", value)` where `xxx` is the solver-specific string.
