### ISSUE TITLE
Return feasible solution when time limit is reached

### ISSUE THREAD

**Issue by mzy2240** [jump-dev/AmplNLWriter.jl#166]
I am comparing `COPT.jl` with `AmplNLWriter.jl+COPT` now, and one different thing is that `COPT.jl` would return a feasible solution when time limit is reached, while `AmplNLWriter.jl+COPT` would simply raise an `OTHER_ERROR` with 

`Result index of attribute MathOptInterface.ObjectiveValue(1) out of bounds. There are currently 0 solution(s) in the model`. 

`COPT` is not the cause, cause I could reproduce the same issue with `Gurobi`, `HiGHS`, and `Xpress`. Is there a way to return a feasible solution with this package?

**Comment by mzy2240** [comment]
```julia
println("Status: ", termination_status(model))
println("Objective value: ", objective_value(model))
println("x: ", value.(x))
```
This is the output script used in the comparison which raise the error.

**Comment by mzy2240** [comment]
> This depends on the behavior of the AMPL executable. If no solution is written to the `.sol` file, then we can't return it to the user.

I haven't had even one time that it gives a feasible solution when the time limit is reached, which is really surprising. Tried quite some different solvers. All the corresponding `*.jl` could give feasible solution at least.

> Why are you using `AmplNLWriter` and not the `.jl` packages directly?

Cause I only have the license to certain solvers via AMPL, and I am not sure if I could use the `*.jl` package with the AMPL-bundled&licensed solvers.

**Comment by odow** [comment]
> I haven't had even one time that it gives a feasible solution when the time limit is reached, which is really surprising

This might be an artifact of the AMPL executables. There might also be an option that we can set? I'm not sure. 

Here's how we call AMPL: 

https://github.com/jump-dev/AmplNLWriter.jl/blob/80c02896cc32d93f489938b0e86a17146435f3fc/src/AmplNLWriter.jl#L52

Then we parse the `.sol` file. So whether a solution is written to the `.sol` file is out of our control (unless there's an option that we're not setting).

**Comment by mzy2240** [comment]
Is there a way to save (or find the path of) the `.nl` and the `.sol` file? Might be handy for debugging.

**Comment by odow** [comment]
No, but it has come up a few times, so it's probably a reasonable thing to add.

**Comment by odow** [comment]
Can you run `import Pkg; Pkg.pkg"add AmplNLWriter#master"` then restart Julia and run with the new `directory` keyword argument from #167? Then we can see the `.nl` file and the `.sol` file.

**Comment by mzy2240** [comment]
Thanks! Now I am able to obtain both `sol` and `nl` files. And I do find the feasible solution in the `sol` file, tho Julia still shows the inaccurate result

```julia
Gurobi 10.0.1: lim:time=60
Status: OTHER_LIMIT
Result index of attribute MathOptInterface.ObjectiveValue(1) out of bounds. There are currently 0 solution(s) in the model.
```

Here is the `sol` file:
[model.sol.zip](https://github.com/jump-dev/AmplNLWriter.jl/files/11107657/model.sol.zip)

**Comment by mzy2240** [comment]
from cplex
[model.sol 2.zip](https://github.com/jump-dev/AmplNLWriter.jl/files/11107739/model.sol.2.zip)

from copt
[model.sol 3.zip](https://github.com/jump-dev/AmplNLWriter.jl/files/11107751/model.sol.3.zip)

all show feasible solutions

**Comment by mzy2240** [comment]
I am able to locate the issue. It is caused by `_interpret_status` from [here](https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/FileFormats/NL/sol.jl#L208). In my case, gurobi will return 403 as `solve_result_num` and cplex will return 422, and both means `time limit with integer solution`.

**Comment by odow** [comment]
Thanks for this. Let me take a look.

**Comment by odow** [comment]
Ah. I remember now. The issue was that solvers do not uniformly report their status symbols to AMPL, so we can never distinguish feasible points from infeasible points. Here's a selection of "limit" statuses:

https://github.com/ampl/asl/blob/734d52cf203cf5eeb07ad16232933531794d5809/solvers/cplex/README.cplex#L1734-L1752
https://github.com/ampl/asl/blob/734d52cf203cf5eeb07ad16232933531794d5809/solvers/gurobi/README.gurobi#L88-L97
https://github.com/ampl/asl/blob/734d52cf203cf5eeb07ad16232933531794d5809/solvers/minos/README.minos#L128-L129
https://github.com/ampl/asl/blob/734d52cf203cf5eeb07ad16232933531794d5809/solvers/npopt/README#L112

What we can fix, however, is that if there is a primal solution, we can return it, leaving the user to verify whether it is feasible or not.

**Comment by mzy2240** [comment]
Yeah that should work and could cover most of the cases, especially for those OTHER_LIMIT and OTHER_ERROR.

**Comment by odow** [comment]
```julia
function MOI.get(sol::MOI.FileFormats.NL.SolFileResults, ::MOI.ResultCount)
    return isempty(sol.variable_primal) ? 0 : 1
end
```
