### ISSUE TITLE
Support MOI.VariableBasisStatus and MOI.ConstraintBasisStatus attributes

### ISSUE THREAD

**Issue by mzy2240** [jump-dev/AmplNLWriter.jl#169]
Currently when running `lp_sensitivity_report` after getting an optimal solution, the following error would be raised

```julia
Unable to query LP sensitivity information because this solver does not support querying the status of variables in the optimal basis.
```

**Comment by odow** [comment]
AmplNLWriter does not support returning basis information for the variables and constraints.

Can you point to any examples or options where calling an AMPL executable would write out the basis information to the `.sol` file?

**Comment by odow** [comment]
Some solvers return a `sstatus` suffix. Here's a Gurobi solve:
```
shell> cat model.nl
g3 1 1 0
 1 1 1 0 0 0
 0 1
 0 0
 0 0 0
 0 0 0 1
 0 0 0 0 0
 1 1
 0 0
 0 0 0 0 0
C0
n0
O0 1
n0
x1
0 0
r
1 1
b
2 0
k0
J0 1
0 1
G0 1
0 1

shell> cat model.sol
Gurobi 9.5.1: optimal solution; objective 1

Options
3
1
1
0
1
1
1
1
1
1
objno 0 0
suffix 0 1 8 0 0
sstatus
0 1
suffix 1 1 8 0 0
sstatus
0 2
```
but adding basis support to AmplNLWriter seems very niche. Just use the proper solver APIs instead. The NL files are really intended for nonlinear programs.

**Comment by blegat** [comment]
Maybe `lp_sensitivity_report` should skip these attributes instead of erroring then ?

**Comment by odow** [comment]
Closing as won't fix. I don't see a need for this. The solvers which support basis status have corresponding packages with proper APIs.
