### ISSUE TITLE
Support `MOI.NonlinearScalarFunction`

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/AmplNLWriter.jl#177]
This would be especially helpful for extensions like InfiniteOpt to will exclusively use the new nonlinear interface. Once the new version of InfiniteOpt is released, solvers like this will no longer work.

**Comment by odow** [comment]
It does:

https://github.com/jump-dev/AmplNLWriter.jl/blob/4e1edda22d272e3df27893eee7a7ca1e2da19ac9/src/AmplNLWriter.jl#L213

Do you have an example where it doesn't work?

**Comment by pulsipher** [comment]
Quite right, my mistake. I made the classic mistake of assuming it was installed at the latest version. Forcing the package manager to install v1.2 fixes the issue.
