### ISSUE TITLE
MathProgBase.getobjbound()

### ISSUE THREAD

**Issue by mlubin** [jump-dev/AmplNLWriter.jl#42]
When Bonmin terminates because of a timeout, for example, it would be helpful to be able to access the best lower bound it was able to prove. Is this information available in some form? If so, could we expose it via the standard `MathProgBase.getobjbound` method?

**Comment by JackDunnNZ** [comment]
[This](https://groups.google.com/forum/#!topic/ampl/WD3p3EVfwq4) indicates that the support for returning the best bound is solver-specific, with Gurobi and CPLEX both supporting the `bestbound` suffix on the objective to add this info to the output solution file.

I had a quick skim through the Bonmin options (admittedly just a grep for "bound") but couldn't find any similar option there. If it does exist then we might be able to figure a way to get the bound out.

**Comment by odow** [comment]
Closing as won't-fix because there doesn't appear to be a solver-independent (or widely supported) way to do this. If someone knows a way to do this, please comment and I will re-open.
