### ISSUE TITLE
Support quadratic constraints in @constraint

### ISSUE THREAD

**Issue by rb004f** [jump-dev/AmplNLWriter.jl#49]
The following will fail 

```julia
m1 = Model(solver =  BonminNLSolver())
@variable(m1, 0 <= yp <= 1, Int)
@variable(m1, 0 <= l <= 1000.0)
@variable(m1, 0 <= f <= 1000.0)
@constraint(m1, .087*l >= f^2)
@constraint(m1,  l <= yp*1000.0)
try
   solve(m1)
catch e
   println(e)
end
```

because there is a quadratic expression in one of the constraints.  However, this syntax for quadratic constraints is ok for use with the OSIL solvers, Gurobi, cplex, etc.

The current fix is to replace `@constraint` with `@NLConstraint`. However, `@NLConstraint` is incompatible with cplex and Gurobi.  So, while the constraint expression is the same, the functions for expressing them are currently solver dependent.

**Comment by JackDunnNZ** [comment]
AmplNLWriter currently doesn't implement the Quadratic parts of the [LinearQuadratic interface in MathProgBase](https://mathprogbasejl.readthedocs.io/en/latest/lpqcqp.html#quadratic-programming), so it is expected to fail here. This means that you will need to use the Nonlinear interface (i.e. `@NLconstraint`, etc.) to add quadratic terms, as you have found.  We'd welcome any contributions to fill out the missing methods in the LinearQuadratic interface if this is something you need.

**Comment by mlubin** [comment]
One approach would be to implement the expression interface [here](https://github.com/JuliaOpt/MathProgBase.jl/blob/master/src/SolverInterface/nonlinear_to_lpqp.jl), and then you could delete all the LinearQuadratic wrapping code in AmplNLWriter.

**Comment by JackDunnNZ** [comment]
Not sure it's worth doing that, there's not much extra code to begin with, basically just [here](https://github.com/JuliaOpt/AmplNLWriter.jl/blob/master/src/AmplNLWriter.jl#L251). Loading the constraints from the A matrix is a lot faster and easier than doing it via expressions, plus we don't have to check linearity of the expressions and prune off the linear parts etc. Depends how hard it is to implement the missing LinearQuadratic methods I guess

**Comment by ccoffrin** [comment]
I will second that the AMPL writer should support solving QP models.  This is unexpected to AMPL users, who are accustomed to writing QP models as NL files.  And simply promoting your models from QP to NL, is not a viable solution when developing a modeling framework where the solver type is not known a priori.

**Comment by mlubin** [comment]
I don't think there's any opposition to this feature, just lacking someone sufficiently motivated to implement it.

**Comment by ccoffrin** [comment]
My motivation is increasing.  :-)

**Comment by KSepetanc** [comment]
I have tried to run AmplNLWriter with KNITRO and some quadratic constraints (using `@constraints` macro) and also some `@NLconstraints`. To my surprise there was no error and everything was correctly recognized.
Is this issue only related to the Bonmin or it has been solved recently but left open as an issue?

**Comment by ccoffrin** [comment]
I think this issue was resolved with the move to MOI, @odow can you confirm?

**Comment by odow** [comment]
I guess so. I think we left this open for the MPB interface.

**Comment by odow** [comment]
Closing as fixed in MOI. The MPB interface doesn't support them, but we won't be fixing that.
