### ISSUE TITLE
clean_solverdata and tmp files

### ISSUE THREAD

**Issue by ccoffrin** [jump-dev/AmplNLWriter.jl#72]
At some point this package generates `tmp*` files in the `.solverdata` directory.  I did not see the proper way to clean these.  `clean_solverdata` focuses on `.nl` and `.sol` files.

**Comment by odow** [comment]
This should probably just do something like https://github.com/JuliaOpt/AmplNLWriter.jl/blob/master/test/nl_convert.jl#L70-L74

These will only hang around if `write_nl_file` crashes with an exception.
