### ISSUE TITLE
Refactor the interface to call solver binaries

### ISSUE THREAD

**Issue by mlubin** [jump-dev/AmplNLWriter.jl#77]
Ipopt's binary requires ENV variables set before it's called. Rather than set these globally when Ipopt.jl is loaded, the better solution is for Ipopt to export a function that calls the binary within `withenv`. This requires changing how AmplNLWriter calls solvers (the path to the binary isn't sufficient).

https://github.com/JuliaOpt/Ipopt.jl/blob/3da72b6f51a78bb0daf049a9bef12c57944841a0/src/Ipopt.jl#L24

**Comment by odow** [comment]
Closing because nothing needs to change on the AmplNLWriter side of things.

For Julia 1.3+, you can use `Ipopt_jll` by wrapping the optimize call in a function
```Julia
using JuMP, AmplNLWriter, Ipopt_jll
model = Model()
@variable(model, x)
Ipopt_jll.amplexe() do path
    set_optimizer(model, () -> AmplNLWriter.Optimizer(path))
    optimize!(model)
end
```
